export const Blog={

    // Links props
    Link6:"RECENT POSTS",
    Link7:"BLOG POSTS",
    Link8:"PRESS RELEASES",
    Link9:"IN THE NEWS",
    Link10:"Marisa Pangaro",
    Link11:"Promoting Equity in Local Government 2023: Digital and Physical Infrastructure Considerations",
    Link12:"Constituent Engagement,",
    Link13:" Government Efficiency,",
    
    Link14:"Digital Transformation,",
    Link15:"Blog",
    Link16:"The Impact of Equity in Local Government",
    Link17:"Consitituent Experience",
    Link18:"American Rescue Plan",
    Link19:"Public Health",
    // span props
    span1:"By",
    span2:"On March 23 2023",
    span3:"Tags:",
    // h props
    h1:"Government Trends & Technology Blog",
    h3:"Subscribe to our Blog",
    // input name props
    Subscribe:"Subscribe",
    Email:"Email",
    // img props
    img2:"	https://www.govpilot.com/hubfs/Equity.png",
    // p props
    p:"The past few years have been a time of reflection due to societal shifts that have...",
    p2:"(7 mln read)"
}
export const Pricing={
 
    // h title
    h1:"Digital Transformation that Scales for Your Government",
    // p title
    p:"Get your instant price estimate below!",
    // dropdowns
    dropdowntittle:"State *",
    dropdown1:"Select state",
    dropdown2:"Albama",
    dropdown4:"Alaska",
    dropdown5:"American Samoa",
    dropdown6:"Arizona",
    dropdown7:"Arkansas",
    dropdown8:"Bermuda",
    dropdown9:"California",
    dropdown10:"Colorado",
    dropdown11:"Commonwealth of the Nothern Mariana Islands",
    dropdown12:"Connecticut",
    dropdown13:"Delavare",
    dropdown14:"District of columbia",
    dropdown15:"Florida",
    dropdown16:"Georgia",
    dropdown17:"Guam",
    dropdown18:"Hawaii",
    dropdown19:"idaho",
    dropdown20:"Illinois",
    dropdown21:"indiana",
    dropdown22:"Lowa",
    dropdown23:"Kansas",
    dropdown24:"Kentucky",
    dropdown25:"Louisiana",
    dropdown26:"Maine",
    dropdown27:"Maryland",
    dropdown28:"Massachysetts",
    dropdown29:"Michigan",
    dropdown30:"Minnesota",
    dropdown31:"Mississippi",
    dropdown32:"Missouri",
    dropdown33:"Montana",
    dropdown34:"Nebraska",
    dropdown35:"Nevada",
    dropdown36:"New Hampshire",
    dropdown37:"New Jersey",
    dropdown38:"New Mexico",
    dropdown39:"New York",
    dropdown40:"North Carolina",
    dropdown41:"North Dakota",
    dropdown42:"Ohio",
    dropdown43:"Oklahoma",
    dropdown44:"Oregon",
    dropdown45:"Pennsylvania",
    dropdown46:"Puerto Rico",
    dropdown47:"Rhode Island",
    dropdown48:"South Carolina",
    dropdown49:"South Dakota",
    dropdown50:"Tennessee",
    dropdown51:"Texas",
    dropdown52:"United Stated Virgin Islands",
    dropdown53:"Utah",
    dropdown54:"Vermont",
    dropdown55:"Virginia",
    dropdown56:"Washington",
    dropdown57:"West Virginia",
    dropdown58:"Wisconsin",
    dropdown59:"Wyoming",
    // dopdowndiv2
    dropdowntittle2:"Government Type *",
    dropdown60:"Select type",
    dropdown61:"Municipality",
    dropdown62:"County",
  // dopdowndiv3
    dropdowntittle3:"County *",
    
    dropdown63:"Select County",
    dropdown64:"Aluetians East",
    dropdown65:"Aluetians west ",
    dropdown66:"Anchorage",
    dropdown67:"Bethel",
    dropdown68:"Bristol Bay",
    dropdown69:"Denali",
    dropdown70:"Dillingham",
    dropdown71:"Fairbanks North Star",
    dropdown72:"Haines",
    dropdown73:"Hoonah-Angoon",
    dropdown74:"Juneau",
    dropdown75:"Kenai",
    dropdown76:"Peninsula",
    dropdown77:"Ketchikan Gateway",
    dropdown78:"Kodiak Island",
    dropdown79:"Kusilvak",
    dropdown80:"Lake and Peninsula",
    dropdown81:"Matanuska-Susitna",
    dropdown82:"Nome",
    dropdown83:"North Slope",
    dropdown84:"NorthWest Arctic",
    dropdown85:"Petersburg",
    dropdown86:"Prince of wales-Hyder",
    dropdown87:"Sitka",
    dropdownspan:"Government Email Address*",
//    input props
   calculate:"calculate",
   cardtitle:"What is GovPilot?",
   cardicon:">",
   cardp:"GovPilot is a cloud-based government management platform. Our digital modules streamline and organize government operations and services, saving local governments time and money, while making the constituent experience convenient.",
   cardtitle2:"What is a “Templated Module”?",
   cardp2:"Templated Modules are used to perform specific repeatable processes such as business registrations, pet licensing, work orders, reporting a concern, etc. They have been built and enhanced through the collective knowledge and input of many local governments.",
   h2:"Smart Governments Use GovPilot",
   h3:"Frequently Asked Questions",
//    cardimg
   
   cardimg2:"https://www.govpilot.com/hs-fs/hubfs/Bexar%20County.png?width=240&name=Bexar%20County.png",
   cardimg3:"https://www.govpilot.com/hs-fs/hubfs/camden.png?width=240&name=camden.png",
   cardimg4:"https://www.govpilot.com/hs-fs/hubfs/Columbine-2.png?width=240&name=Columbine-2.png",
   cardimg5:"https://www.govpilot.com/hs-fs/hubfs/Curry-County.png?width=240&name=Curry-County.png",
   cardimg6:"https://www.govpilot.com/hs-fs/hubfs/Harvey.png?width=240&name=Harvey.png",
   cardimg7:"https://www.govpilot.com/hs-fs/hubfs/Hermiston.png?width=240&name=Hermiston.png",
   cardimg8:"https://www.govpilot.com/hs-fs/hubfs/Hudson-County…dth=240&name=Hudson-County-Seal-Transparent-1.png",
   cardimg9:"https://www.govpilot.com/hs-fs/hubfs/Jackson-County.png?width=240&name=Jackson-County.png",
   cardimg10:"https://www.govpilot.com/hs-fs/hubfs/jersey-city.png?width=240&name=jersey-city.png",
   cardimg11:"https://www.govpilot.com/hs-fs/hubfs/ocoee.png?width=240&name=ocoee.png",
   cardimg12:"https://www.govpilot.com/hs-fs/hubfs/Trenton2.png?width=240&name=Trenton2.png",
 
    //  cardtitle props
    cardtitle3:"Bexar County, TX",
    cardtitle4:"Buffalo, NY",
    cardtitle5:"Camden County, NJ",
    cardtitle6:"Columbine Valley, CO",
    cardtitle7:"Curry County, OR",
    cardtitle8:"Harvey, IL",
    cardtitle9:"Hermiston, OR",
    cardtitle10:"Hudson County, NJ",
    cardtitle11:"Jackson County, MS",
    cardtitle12:"Jersey City, NJ", 
    cardtitle13:"Ocoee, FL",
    cardtitle14:"Trenton, NJ",
        //  dropdown email
    emailjohn:"john.doe@mycity.gov",
   
    // card 5
    // card1
    packages:"Packages",
    cardtext:"Getting started is easy.",
    cardtext2:" Book a 15-minute Consulatation",
    cardbtn2:"Book Consultation",
    cardlist:"GIS Map",
    cardlist2:"Report a Concern App",
    cardlist3:"Unlimited Users & Support",
    cardlist4:"Weekly Engagement Reporting",
    cardlist5:"Dedicated Account Manager",
    
    // 
    cardheader:"ESSENTIALS",
    cardh1:"5",
    cardspan:"Templated Mole",
    cardspan2:"$ --- ",
    cardpp:"per month (billed annually)",
    cardpp2:"Price per Module",
    cardbtn:"Learn More",


    cardh2:"10",
    cardh3:"20",
    cardh4:"125",
    // cardheader name
    cardheader2:"PROFESSIONAL", 
    cardheader3:"ENTERPRISE",
    cardheader4:"UNLIMITED",
    // acordion
    acordionspan:" How is GovPilot's pricing determined?",
    acordionp:"  GovPilot's pricing is straightforward, based on two factors - population size and number of modules selected. This makes GovPilot accessible for local governments of all sizes - from small towns and villages to large cities and counties. ",
    acordionp2:"This also enables governments to start with a few modules or with one department, and scale across the full government organization as the need arises. ",
    acordionspan2:"How many users / login seats do we have to pay for?",
    acordionp3:"None! Your purchase of GovPilot comes with unlimited user login accounts no matter how many modules you select! Every official and employee can log in GovPilot with their own credentials at NO additional cost. ",
    acordionspan3:"Which local governments currently use GovPilot?",
    acordionp4:"We are proud to have partnered with local governments of all sizes, across the United States and Canada since our founding in 2015. Some examples include:",
    acordionp5:"Buffalo, NY | Columbine Valley, CO | Harvey, IL | Hermiston, OR | Trenton, NJ | Jersey City, NJ ",
    acordionp6:"Elizabeth, NJ | Chapel Hill, NC | South Orange, NJ | Ocean Beach, NY | Jackson County, MS | Hudson County, NJ",
    acordionp7:"Bexar County, TX | Bergen County, NJ | Camden County, NJ | Curry County, OR |Macon-Bibb County, GA | Ontario, Canada",
    acordionspan4:"What do I need to provide GovPilot in order to get our GIS Map set up?",
    acordionp8:"All we need is a shape (.shp) file of your parcels.  This is usually held with your engineering or GIS department.",
    acordionspan5:"What is the Report-a-Concern feature and the GovAlert app?",
    acordionp9:"A link on your government's website (Report-a -Concern) and a mobile app (",
    acordionp10:"GovAlert",
    acordionp11:") available for Android and iOS devices which enables residents to snap a geo-tagged picture of a pothole, overgrowth, damaged street sign, or other non-emergency along with a description of the situation. Whether submitted via the GovAlert mobile app downloaded to their phone, or the GovPilot digital form on their town's website, the concern is geo-tagged on the municipality's GIS map and routed to the appropriate government official, who receives the alert in real-time. Departments can track the status of hazards as they are reported, the dispatch of personnel to address needs and the updating of constituents on repair and resolution statuses in real-time. "
}