export const obj={
    // nav
      // img props
      imgg:"https://www.govpilot.com/hs-fs/hubfs/govpilot_logo.png?width=150&name=govpilot_logo.png",
      // Links props
      LInk1:"Solutions",
      LInk2:"Pricing",
      LInk3:"Case Studios",
      LInk4:"Blog & News",
      LInk5:"About Us",
      
      // button props
      button1:"Get Demo",
      button2:"Sign in",
  

    img:"https://www.govpilot.com/hs-fs/hubfs/govpilot_logo.png?width=100&name=govpilot_logo.png",
    a1:"Solutions",
    a2:"Pricing",
    a3:"Case Studies",
    a4:"Blog & News",
    a5:"About Us",
    a6:"The Operating  SystemFor Local Government",
    a7:"Modern government management software that streamlines operations and services by automating processes, unifying data, and engaging constituents.",
    img2:"https://www.govpilot.com/hs-fs/hubfs/GovPilot19/capterra.png?width=140&height=90&name=capterra.png",
    a8:"Capterra Customer Reviews",
    a9:"Among Capterra's highest rating and most reviewed for Government Software",
    a10:"4.7 / 5 Star rating ",
    a11:"Best Ease of Use",
    a12:"Best Functionality & Features Government Software",
    a13:"Best Customer Support Government Software",
    a14:"Most Recommended Government Software",
    img3:"https://www.govpilot.com/hubfs/2023%20GovTech%20100%20Badge%20(1)-1.webp",
    a15:"Award Winning Software",
    a16:"Named a GovTech100 Company for Six Consecutive Years 2018 - 2023",
    a17:"The GovTech 100 is an annual list published by Government Technology Magazine of 100 companies focused on, making a difference in, and selling to state and local government agencies across the United States.",
    z1:"Do More with Fewer Resources",
    z2:"Say Goodbye to Paper and Single-Purpose Software. GovPilot integrates your departments and data on one platform.",
    img4:"	https://2857984.fs1.hubspotusercontent-na1.net/hubfs/2857984/2020%20GovPilot%20Brand%20Explainer%20Video.mp4/medium.jpg?t=1673559821230",
    z3:"125+ Solutions for All Departments",
    z4:"Implement best-in-class digital processes and workflows that have been built with input from real-world users in local government.",
    z5:"See Solutions >>",
    z6:"Mobile Apps",
    z7:"Empower citizens to quickly report concerns from their phone and enable mobile, table-based inspections.",
    z8:"GovAlert App  /  GovInspect App",
    z9:"See How GovPilot Works",
    z10:"125+ digital modules with gold standard workflows enable efficient digital services and operations for local governments of all sizes.",
    img5:"	https://www.govpilot.com/hubfs/How%20It%20Works/ic_01_auto.svg",
    z11:"Automate",
    z12:"Save Time & Resources",
    z13:"End-to-end digital forms, automated workflows, and user-friendly GIS maps enable staff to eliminate paper and manual tasks, saving hours per week and making government more efficient, productive, and responsive.",
    z14:"Learn How to Automate with GovPilot >>",
    img6:"https://www.govpilot.com/hubfs/hm_CTA_L%20(1).webp",
    z15:"https://www.govpilot.com/hubfs/Sub_02_Unify-2.webp",
    z16:"	https://www.govpilot.com/hubfs/How%20It%20Works/ic_02_unify.svg",
    z17:"Unify",
    z18:"Eliminate Data Silos",
    z19:"GovPilot's PropertyProfile eliminates data and communications silos by displaying parcel level detail including cross departmental records. Data updates in real-time and is accessible from anywhere with a WIFI connection, 24/7.",
    z20:"Learn how to Unify Data with GovPilot >>",
    img7:"	https://www.govpilot.com/hubfs/Sub_03_Engage-3.webp",
    img8:"	https://www.govpilot.com/hubfs/How%20It%20Works/ic_01_auto.svg",
    z21:"Engage",
    z22:"Deliver Convenience",
    z23:"In today's world, constituents expect convenient digital services and the ability to engage with their government. Digital forms, automated workflows, and mobile apps - GovAlert and GovInspect - deliver ease of use, transparency, and responsiveness. ",
    z24:"Learn How to Engage with GovPilot >>",
    img9:"	https://www.govpilot.com/hubfs/Sub_04_Manage-3.webp",
    img10:"	https://www.govpilot.com/hubfs/How%20It%20Works/ic_04_manage.svg",
    z25:"Manage",
    z26:"Get Detailed Insights",
    z27:"GovPilot's modern government management software makes data visualization and reporting straightforward. Save hours of work. Pull data and generate reports with just a click. Make smarter, more informed decisions faster. ",
    z28:"Learn How to Manage with GovPilot >>",

    // main2 props
    x1:"Proven Results",
    x2:"Trusted by municipal, county, and state governments, large and small.",
    x3:"All Case Studies >>",
    x4:"Pricing that Scales for your Government",
    x5:"Straightforward pricing based on population and number of modules selected makes GovPilot accessible for local governments of all sizes - from small towns to large cities and counties.",
    x6:"Get an Instant Price Quote>>",
    x7:"ESSENTIALS",
    x8:"5 templated modules. Unlimited users & support.",
    x9:"Blog and News",
    x10:"Get the latest GovPilot news, updates, and announcements ",
    x11:"from the GovPilot blog.",
    zeus:"All Blog Posts >>",



    // footer

    // p props
    cardtitle1:"204 East Main Street",
    cardtitle2:"Manasquan, NJ 08736",
    cardtitle3:"(888) 711-3399",
    footerp1:"©2015 - 2023 GOVPILOT. ALL RIGHTS RESERVED",
    footerp2:" 800.491.6732",
    // Links props
    Link20:"sales@govpilot.com",
    // icon props
    Link21:"Products & Solutions",
    Link22:"Integrations & Partnerships",
    Link23:"Federal Relief",
    Link24:"Case Studies",
    Link25:"Our Clients",
    Link26:"Contact Us",
    Link27:"About GovPilot",
    Link28:"Advisory Board",
    Link29:"Careers",
    Link30:"Blog & News",
    Link31:"Privacy Policy",
    Link32:"Security Overview",
    Link33:" PRIVACY POLICY",
    Link34:" info@govpilot.com",
    // img props
    imga:"https://www.govpilot.com/hubfs/2023%20GovTech%20100%20Badge-1.webp",
    imgb:"https://www.govpilot.com/hubfs/website-2022/govtech-2022.webp",
    imgd:"https://www.govpilot.com/hubfs/website-2022/govtech_2021.webp",
    imge:"https://www.govpilot.com/hubfs/website-2022/govtech_2019.webp",
    imgr:"https://www.govpilot.com/hubfs/website-2022/govtech_2018.webp",
} 
   export const obj1=[
    {
     a:"https://www.govpilot.com/hubfs/big-bear-lake-logo.webp",
     b:"https://www.govpilot.com/hubfs/Columbine-1.png",
     c:"https://www.govpilot.com/hubfs/Eastampton%20NJ.png",
     d:"https://www.govpilot.com/hubfs/Hudson%20County%2c%20NJ%20Seal.png", 
     e:"https://www.govpilot.com/hubfs/Millsboro%20Seal.png",
     f:"https://www.govpilot.com/hubfs/Trenton.png",
     g:"https://www.govpilot.com/hubfs/Watauga%20TX-1.png",
   
   },
    {
     img1:"https://www.govpilot.com/hubfs/Big%20Bear%20Image.jpg",
     img:"https://www.govpilot.com/hubfs/LarryVaupel.jpg",
      p:"Case Study: Big Bear Lake, CA",
     p1:"There is a night and day difference with GovPilot. It has more than paid for itself through Report-a-Concern and the easy collection of fines and citations.",
     p2:"Lawrence Vaupel",
     p3:"Director of Tourism Management",
     p4:"24 Days Saved",
     p5:"Processing paper renewals previously took 15 minutes per paper application. Multiplied by 2,300 properties is 24 days worth of time saved with GovPilot!",
     a:"Read the Case Study",
   },
   { 
     img1:"https://www.govpilot.com/hubfs/Columbine%20Valley.jpg",
     img:"https://www.govpilot.com/hubfs/Anrea%20Gardner%20Square.png",
     p:"Case Study: Watauga, TX",
     p1:"The beauty of GovPilot is that it eliminates the complexity of our old manual process and puts everything at our fingertips. Work that used to take days, now takes minutes.",
     p2:"Andrea Gardner",
     p3:"City Manager",
     p4:"97%Time Savings",
     p5:"Employees now take less than two minutes to enter information and instantly update the system rather than manually entering handwritten notes into Excel.",
     a:"Read the Case Study",
   
   },
   {
     img1:"https://www.govpilot.com/hubfs/Big%20Bear%20Image.jpg",
     img:"https://www.govpilot.com/hubfs/LarryVaupel.jpg",
      p:"Case Study: Big Bear Lake, CA",
     p1:"There is a night and day difference with GovPilot. It has more than paid for itself through Report-a-Concern and the easy collection of fines and citations.",
     p2:"Lawrence Vaupel",
     p3:"Director of Tourism Management",
     p4:"24 Days Saved",
     p5:"Processing paper renewals previously took 15 minutes per paper application. Multiplied by 2,300 properties is 24 days worth of time saved with GovPilot!",
     a:"Read the Case Study",
   },
   { 
     img1:"https://www.govpilot.com/hubfs/Columbine%20Valley.jpg",
     img:"https://www.govpilot.com/hubfs/Anrea%20Gardner%20Square.png",
     p:"Case Study: Watauga, TX",
     p1:"The beauty of GovPilot is that it eliminates the complexity of our old manual process and puts everything at our fingertips. Work that used to take days, now takes minutes.",
     p2:"Andrea Gardner",
     p3:"City Manager",
     p4:"97%Time Savings",
     p5:"Employees now take less than two minutes to enter information and instantly update the system rather than manually entering handwritten notes into Excel.",
     a:"Read the Case Study",
   
   },
   {
     img1:"https://www.govpilot.com/hubfs/Big%20Bear%20Image.jpg",
     img:"https://www.govpilot.com/hubfs/LarryVaupel.jpg",
      p:"Case Study: Big Bear Lake, CA",
     p1:"There is a night and day difference with GovPilot. It has more than paid for itself through Report-a-Concern and the easy collection of fines and citations.",
     p2:"Lawrence Vaupel",
     p3:"Director of Tourism Management",
     p4:"24 Days Saved",
     p5:"Processing paper renewals previously took 15 minutes per paper application. Multiplied by 2,300 properties is 24 days worth of time saved with GovPilot!",
     a:"Read the Case Study",
   },
   { 
     img1:"https://www.govpilot.com/hubfs/Columbine%20Valley.jpg",
     img:"https://www.govpilot.com/hubfs/Anrea%20Gardner%20Square.png",
     p:"Case Study: Watauga, TX",
     p1:"The beauty of GovPilot is that it eliminates the complexity of our old manual process and puts everything at our fingertips. Work that used to take days, now takes minutes.",
     p2:"Andrea Gardner",
     p3:"City Manager",
     p4:"97%Time Savings",
     p5:"Employees now take less than two minutes to enter information and instantly update the system rather than manually entering handwritten notes into Excel.",
     a:"Read the Case Study",
   
   },
   {
     img1:"https://www.govpilot.com/hubfs/Big%20Bear%20Image.jpg",
     img:"https://www.govpilot.com/hubfs/LarryVaupel.jpg",
      p:"Case Study: Big Bear Lake, CA",
     p1:"There is a night and day difference with GovPilot. It has more than paid for itself through Report-a-Concern and the easy collection of fines and citations.",
     p2:"Lawrence Vaupel",
     p3:"Director of Tourism Management",
     p4:"24 Days Saved",
     p5:"Processing paper renewals previously took 15 minutes per paper application. Multiplied by 2,300 properties is 24 days worth of time saved with GovPilot!",
     a:"Read the Case Study",
   },
   ]